spring:
  application:
    name: PXL
    version: 1.0.0

  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/template?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource #使用Druid数据库连接池
    #druid配置
    #配置初始化大小/最小/最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    #获取连接等待超时时间
    maxWait: 60000
    #间隔多久进行一次检测，检测需要关闭的空闲连接
    timeBetweenEvictionRunsMillis: 60000
    #一个连接在池中最小生存的时间
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties:
      druid:
        stat:
          mergeSql: true
          slowSqlMillis: 5000
redis:
  host: 127.0.0.1
  port: 6379
  password:
  pool:
    maxTotal: 10
    maxWait: 5
    maxIdle: 2
    minIdle: 3000

#  rabbitmq:
#    host: 39.106.62.18
#    port: 5672
#    username: guest
#    password: guest

server:
  port: 8006



#logging.level.xx指定包路径xx=trace
logging:
  level:
    root: info
    com:
      pxl:
        mapper: debug
  file:
    #path: output/logs
    path: output/pxl.log #可以指定绝对路径
  pattern:
    console: "%red(%d{yyyy-MM-dd HH:mm:ss}) %green([%thread]) %highlight(%-5level) %boldMagenta(%logger{36}) %blue(%msg%n)"

mybatis:
  configuration:
    mapUnderscoreToCamelCase: true


jwt:
  header: Authorization
  # 令牌前缀
  token-start-with: Bearer
  # 必须使用最少88位的Base64对该令牌进行编码
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  # 在线用户key
  Online-key: -token-
  # 令牌过期时间 此处单位/毫秒 ，默认2小时
  token-validity-in-seconds: 7200000
  # token 续期检查时间范围（默认30分钟，单位默认毫秒），在token即将过期的一段时间内用户操作了，则给用户的token续期
  detect: 1800000
  # 续期时间范围，默认 1小时，这里单位毫秒
  renew: 3600000